# Generated by Django 2.0.1 on 2018-01-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foteczki', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='path',
        ),
        migrations.AddField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='static'),
        ),
    ]
