# Generated by Django 2.0.1 on 2018-01-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foteczki', '0002_auto_20180118_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='.'),
        ),
    ]
