# Generated by Django 2.0.1 on 2018-01-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foteczki', '0005_auto_20180118_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='home/konrad/Pulpit/Instantgram/Instantgram/foteczki/images'),
        ),
    ]
